apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE # create this db on startup
              valueFrom:
                configMapKeyRef:
                  name: lmg-config # configMap name
                  key: mysqlDbname
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lmg-secrets # secret name
                  key: mysqlRootPassword
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          #   gcePersistentDisk:
          #     pdName: <volume-name>
          #     fsType: ext4
          persistentVolumeClaim:
            claimName: mysql-disk

