apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ftb-backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ftb-backend
    spec:
      containers:
        - name: ftbbackend
          image: us.gcr.io/k8s-belgrade-workshop/ftbbackend:1.1
          ports:
            - containerPort: 8080
